#The sequence of triangle numbers is generated by adding the natural numbers.
#The 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
#What is the value of the first triangle number to have over
#five hundred divisors?


counter = 1
number = 0
while True:
    factor_list = []
    divisor_total = 0
    number += counter #finds next triangular number
    for x in range(2,(int(number ** .5) + 1)):
        if number % x == 0:
            factor_list.extend([int((number/x)), x])
    if len(factor_list) > 500:
        print(number)
        break
    counter += 1
